
# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# remap to open new kitty tab in the same directory (default is home dir)
# map ctrl+shift+t            new_tab_with_cwd

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
# input_delay 0
# repaint_delay 2
# sync_to_monitor no
# wayland_enable_ime no

# This is the configuration file for kitty terminal
# For more information, see https://sw.kovidgoyal.net/kitty/conf.html
# For your custom configurations, put it in ./kitty.conf
font_family CaskaydiaCove Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
enable_audio_bell yes
audio_bell_volume 1.0
visual_bell no
bell_on_tab yes
bell_path /usr/share/sounds/freedesktop/stereo/bell.oga
# bell_path /usr/share/sounds/freedesktop/stereo/bell.oga
# visual_bell_duration 0.0
font_size 10.5
window_padding_width 15
cursor_trail 1

# Themes can override any settings in this file
# include theme.conf
#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0
