$primary_paletteKeyColor = 9d6591
$secondary_paletteKeyColor = 887081
$tertiary_paletteKeyColor = 9d6b5a
$neutral_paletteKeyColor = 7e7479
$neutral_variant_paletteKeyColor = 80747b
$background = 181216
$onBackground = ecdfe5
$surface = 181216
$surfaceDim = 181216
$surfaceBright = 3f373c
$surfaceContainerLowest = 120c11
$surfaceContainerLow = 201a1e
$surfaceContainer = 241e22
$surfaceContainerHigh = 2f282c
$surfaceContainerHighest = 3a3337
$onSurface = ecdfe5
$surfaceVariant = 4e444b
$onSurfaceVariant = d2c2cb
$inverseSurface = ecdfe5
$inverseOnSurface = 362e33
$outline = 9a8d95
$outlineVariant = 4e444b
$shadow = 000000
$scrim = 000000
$surfaceTint = f3b2e4
$primary = f3b2e4
$onPrimary = 4d1f47
$primaryContainer = 67355e
$onPrimaryContainer = ffd7f3
$inversePrimary = 814c77
$secondary = dbbed1
$onSecondary = 3e2a39
$secondaryContainer = 554050
$onSecondaryContainer = f8daee
$tertiary = f5b9a5
$onTertiary = 4c2619
$tertiaryContainer = ba8472
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = ffd7f3
$primaryFixedDim = f3b2e4
$onPrimaryFixed = 340830
$onPrimaryFixedVariant = 67355e
$secondaryFixed = f8daee
$secondaryFixedDim = dbbed1
$onSecondaryFixed = 271624
$onSecondaryFixedVariant = 554050
$tertiaryFixed = ffdbcf
$tertiaryFixedDim = f5b9a5
$onTertiaryFixed = 321207
$onTertiaryFixedVariant = 663c2d
$term0 = 353434
$term1 = f946bf
$term2 = ffbac2
$term3 = ffdde6
$term4 = b3a2d5
$term5 = de92c7
$term6 = ffba93
$term7 = ecd2d8
$term8 = b19ea3
$term9 = ff7acb
$term10 = ffd2d5
$term11 = fff1f3
$term12 = babfdd
$term13 = eeaad6
$term14 = ffd1c0
$term15 = ffffff
$rosewater = feedf3
$flamingo = f7dae8
$pink = ffcff1
$mauve = f0a8ec
$red = f097d3
$maroon = eaacd1
$peach = ffbad8
$yellow = ffedf0
$green = ffd8c5
$teal = dedcff
$sky = ebd1ff
$sapphire = e4b6fe
$blue = e3a8f2
$lavender = f0bbf6
$klink = a773bf
$klinkSelection = a872bf
$kvisited = b761b2
$kvisitedSelection = b761b1
$knegative = dd51b3
$knegativeSelection = dd51b2
$kneutral = ff7fc2
$kneutralSelection = ff80c0
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = ecdfe5
$subtext1 = d2c2cb
$subtext0 = 9a8d95
$overlay2 = 877b82
$overlay1 = 73686e
$overlay0 = 61575d
$surface2 = 4f464c
$surface1 = 3d353a
$surface0 = 2b2328
$base = 181216
$mantle = 181216
$crust = 171115
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
