source = $HOME/.config/hypr/modules/variables.conf

source = $HOME/.config/hypr/modules/monitor.conf

source = $HOME/.config/hypr/modules/plugins.conf
source = $HOME/.config/hypr/modules/autostarts.conf


source = $HOME/.config/hypr/modules/general.conf
source = $HOME/.config/hypr/modules/decoration.conf
source = $HOME/.config/hypr/modules/animations.conf

source = $HOME/.config/hypr/modules/theme.conf

source = $HOME/.config/hypr/modules/env.conf

source = $HOME/.config/hypr/modules/keybinds.conf

source = $HOME/.config/hypr/modules/rules.conf
source = $HOME/.config/hypr/modules/input.conf

source = $HOME/.config/hypr/modules/nvidia.conf

source = $HOME/.config/hypr/modules/misc.conf
