# exec = hyprctl dispatch submap global
# submap = global

## Shell keybinds
# Launcher
bind = SUPER, Space , global, caelestia:launcher
# bindin = Super, catchall, global, caelestia:launcherInterrupt
# bindin = Super, mouse:272, global, caelestia:launcherInterrupt
# bindin = Super, mouse:273, global, caelestia:launcherInterrupt
# bindin = Super, mouse:274, global, caelestia:launcherInterrupt
# bindin = Super, mouse:275, global, caelestia:launcherInterrupt
# bindin = Super, mouse:276, global, caelestia:launcherInterrupt
# bindin = Super, mouse:277, global, caelestia:launcherInterrupt
# bindin = Super, mouse_up, global, caelestia:launcherInterrupt
# bindin = Super, mouse_down, global, caelestia:launcherInterrupt

bind = SUPER ALT, O, global, caelestia:dashboard

bind = SUPER, W, exec, caelestia wallpaper -r

# Misc
bind = CTRL ALT, DELETE, global, caelestia:session
bindl = SUPER ALT, N, global, caelestia:clearNotifs
bind = SUPER SHIFT, O, global, caelestia:showall
bind = SUPER, L, global, caelestia:lock

# Brightness
bindl = , XF86MonBrightnessUp, global, caelestia:brightnessUp
bindl = , XF86MonBrightnessDown, global, caelestia:brightnessDown

# Media
bindl = , XF86AudioPlay, global, caelestia:mediaToggle
bindl = , XF86AudioPause, global, caelestia:mediaToggle
bindl = , XF86AudioNext, global, caelestia:mediaNext
bindl = , XF86AudioPrev, global, caelestia:mediaPrev
bindl = , XF86AudioStop, global, caelestia:mediaStop

# Toggle special workspace
bind = SUPER SHIFT CTRL, S, exec, caelestia toggle specialws


# Special workspace toggles
# bind = $kbSystemMonitor, exec, caelestia toggle sysmon
# bind = $kbMusic, exec, caelestia toggle music
# bind = $kbCommunication, exec, caelestia toggle communication
# bind = $kbTodo, exec, caelestia toggle todo

# Utilities
bindl = , Print, exec, caelestia screenshot  # Full screen capture > clipboard
bind = Super CTRL, S, global, caelestia:screenshotFreeze  # Capture region (freeze)
bind = Super CTRL ALT, S, global, caelestia:screenshot  # Capture region
bind = Super SHIFT, R, exec, caelestia record -s  # Record screen with sound
bind = SUPER SHIFT CTRL , R, exec, caelestia record  # Record screen
bind = SUPER CTRL , R, exec, caelestia record -r  # Record region
bind = Super+Shift, C, exec, hyprpicker -a  # Colour picker

# Sleep
bind = Super+Shift, L, exec, systemctl suspend-then-hibernate

# Clipboard and emoji picker
bind = Super, V, exec, pkill fuzzel || caelestia clipboard
bind = Super+Alt, V, exec, pkill fuzzel || caelestia clipboard -d
bind = Super, Period, exec, pkill fuzzel || caelestia emoji -p
bindl = Ctrl+Shift+Alt, V, exec, sleep 0.5s && ydotool type -d 1 "$(cliphist list | head -1 | cliphist decode)"  # Alternate paste

# Testing
# bindl = Super+Alt, f12, exec, notify-send -u low -i dialog-information-symbolic 'Test notification' "Here's a really long message to test truncation and wrapping\nYou can middle click or flick this notification to dismiss it!" -a 'Shell' -A "Test1=I got it!" -A "Test2=Another action"
