general {
    gaps_in = $gaps_in
    gaps_out = $gaps_out

    border_size = $border_size

    # col.active_border = $active_border_col1 $active_border_col2 $active_border_angle
    col.active_border = $active_border_col1
    # col.inactive_border = $inactive_border_col1 $inactive_border_col2 $inactive_border_angle
    col.inactive_border = $inactive_border_col1

    resize_on_border = $resize_on_border
    allow_tearing = $allow_tearing

    layout = $layout
}

