input {
    kb_layout = $kb_layout
    kb_variant = $kb_variant
    kb_model = $kb_model
    kb_options = $kb_options
    kb_rules = $kb_rules

    follow_mouse = $follow_mouse

    sensitivity = $global_sensitivity

    touchpad {
        natural_scroll = $touchpad_natural_scroll
    }
}


gesture = $gesture_fingers, $gesture_direction, $gesture_action


device {
    name = $device_name
    sensitivity = $device_sensitivity
}

