dwindle {
    pseudotile = $dwindle_pseudotile
    preserve_split = $dwindle_preserve_split
}


master {
    new_status = $master_new_status
}


misc {
    force_default_wallpaper = $force_default_wallpaper
    disable_hyprland_logo = $disable_hyprland_logo
}

