plugin {

    hyprexpo {
        columns = $expo_columns
        gap_size = $expo_gap_size
        bg_col = $expo_bg_color
        workspace_method = $expo_workspace_method

        gesture_distance = $expo_gesture_distance
    }

    hyprscrolling {
        # focus_fit_method = $scroll_focus_fit_method
        follow_focus = $scroll_follow_focus
        column_width = $scroll_column_width
        fullscreen_on_one_column = $scroll_fullscreen_one_column
        max_columns = $scroll_max_columns
    }
}

