windowrule {
    name = suppress-maximize-events
    match:class = $rule_suppress_class

    suppress_event = $rule_suppress_event
}

windowrule {
    name = fix-xwayland-drags
    match:class = $rule_xwayland_class
    match:title = $rule_xwayland_title
    match:xwayland = $rule_xwayland_enabled
    match:float = $rule_xwayland_float
    match:fullscreen = $rule_xwayland_fullscreen
    match:pin = $rule_xwayland_pin

    no_focus = $rule_xwayland_no_focus
}

windowrule {
    name = move-hyprland-run
    match:class = $run_class

    move = $run_move_position
    float = $run_float
}

permission = $hyprpm_path, $hyprpm_permission_type, $hyprpm_permission_action

