# ############# Themes #############

env = QT_QPA_PLATFORMTHEME, $qt_platform_theme
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, $qt_disable_window_deco
env = QT_AUTO_SCREEN_SCALE_FACTOR, $qt_auto_scale

env = XCURSOR_THEME, $cursor_theme
env = XCURSOR_SIZE, $cursor_size

env = QT_STYLE, $qt_style
env = QT_COLOR_SCHEME, $qt_color_scheme
env = QT_FONT, $qt_font
env = QT_FONT_SIZE, $qt_font_size
env = QT_ICON_THEME, $qt_icon_theme

# ######## Toolkit Backends ########

env = GDK_BACKEND, $gdk_backend
env = QT_QPA_PLATFORM, $qt_platform
env = SDL_VIDEODRIVER, $sdl_videodriver
env = CLUTTER_BACKEND, $clutter_backend
env = ELECTRON_OZONE_PLATFORM_HINT, $electron_ozone_hint

# ####### XDG Specifications #######

env = XDG_CURRENT_DESKTOP, $xdg_current_desktop
env = XDG_SESSION_TYPE, $xdg_session_type
env = XDG_SESSION_DESKTOP, $xdg_session_desktop

# ############# Others #############

env = _JAVA_AWT_WM_NONREPARENTING, $java_wm_nonreparenting

